export interface Fighter {name: string; icon: string; }

export const fighters = [
    {name: 'Bayonetta', icon: 'bayonetta'},
    {name: 'Captain Falcon', icon: 'captain'},
    {name: 'Chrom', icon: 'chrom'},
    {name: 'Cloud', icon: 'cloud'},
    {name: 'Daisy', icon: 'daisy'},
    {name: 'King Dedede', icon: 'dedede'},
    {name: 'Diddy Kong', icon: 'diddy'},
    {name: 'Donkey Kong', icon: 'donkey'},
    {name: 'Duck Hunt', icon: 'duckhunt'},
    {name: 'Falco', icon: 'falco'},
    {name: 'Fox', icon: 'fox'},
    {name: 'Mr. Game & Watch', icon: 'gamewatch'},
    {name: 'Ganondorf', icon: 'ganon'},
    {name: 'Incineroar', icon: 'gaogaen'},
    {name: 'Greninja', icon: 'gekkouga'},
    {name: 'Ice Climbers', icon: 'ice_climber'},
    {name: 'Ike', icon: 'ike'},
    {name: 'Inkling', icon: 'inkling'},
    {name: 'Joker', icon: 'jack'},
    {name: 'Corrin', icon: 'kamui'},
    {name: 'Ken', icon: 'ken'},
    {name: 'Kirby', icon: 'kirby'},
    {name: 'Bowser', icon: 'koopa'},
    {name: 'Bowser Jr.', icon: 'koopajr'},
    {name: 'King K. Rule', icon: 'krool'},
    {name: 'Link', icon: 'link'},
    {name: 'Little Mac', icon: 'littlemac'},
    {name: 'Lucario', icon: 'lucario'},
    {name: 'Lucas', icon: 'lucas'},
    {name: 'Lucina', icon: 'lucina'},
    {name: 'Luigi', icon: 'luigi'},
    {name: 'Mario', icon: 'mario'},
    {name: 'Dr. Mario', icon: 'mariod'},
    {name: 'Marth', icon: 'marth'},
    {name: 'Meta Knight', icon: 'metaknight'},
    {name: 'Mewtwo', icon: 'mewtwo'},
    {name: 'Mii Fighter', icon: 'miifighter'},
    {name: 'Mii Gunner', icon: 'miigunner'},
    {name: 'Mii Swordsman', icon: 'miiswordsman'},
    {name: 'Ness', icon: 'ness'},
    {name: 'Piranha Plant', icon: 'packun'},
    {name: 'Pacman', icon: 'pacman'},
    {name: 'Palutena', icon: 'palutena'},
    {name: 'Peach', icon: 'peach'},
    {name: 'Pichu', icon: 'pichu'},
    {name: 'Pikachu', icon: 'pikachu'},
    {name: 'Olimar', icon: 'pikmin'},
    {name: 'Pit', icon: 'pit'},
    {name: 'Dark Pit', icon: 'pitb'},
    {name: 'Pokemon Trainer', icon: 'ptrainer'},
    {name: 'Jigglypuff', icon: 'purin'},
    {name: 'Robin', icon: 'reflet'},
    {name: 'Richter', icon: 'richter'},
    {name: 'Ridley', icon: 'ridley'},
    {name: 'Rob', icon: 'robot'},
    {name: 'Megaman', icon: 'rockman'},
    {name: 'Rosalina & Luma', icon: 'rosetta'},
    {name: 'Ryu', icon: 'ryu'},
    {name: 'Samus', icon: 'samus'},
    {name: 'Dark Samus', icon: 'samusd'},
    {name: 'Sheik', icon: 'sheik'},
    {name: 'Isabelle', icon: 'shizue'},
    {name: 'Shulk', icon: 'shulk'},
    {name: 'Simon', icon: 'simon'},
    {name: 'Snake', icon: 'snake'},
    {name: 'Sonic', icon: 'sonic'},
    {name: 'Zero Suit Samus', icon: 'szerosuit'},
    {name: 'Toon Link', icon: 'toonlink'},
    {name: 'Wario', icon: 'wario'},
    {name: 'Wii Fit Trainer', icon: 'wiifit'},
    {name: 'Wolf', icon: 'wolf'},
    {name: 'Yoshi', icon: 'yoshi'},
    {name: 'Young Link', icon: 'younglink'},
    {name: 'Zelda', icon: 'zelda'}
]